# Generated by Django 3.1.2 on 2021-07-20 06:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gallerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='Developer_pic')),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_Name', models.CharField(max_length=100, null=True)),
                ('Owner_pic', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('House_address', models.TextField()),
                ('House_video', models.FileField(null=True, upload_to='Housevideos/%Y/%m/%d/', verbose_name='')),
                ('Building_img1', models.ImageField(upload_to='Housepic')),
                ('Room_img1', models.ImageField(upload_to='Housepic')),
                ('Room_img2', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('Room_img3', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('Landmark', models.TextField()),
                ('House_Location_link', models.URLField(blank=True, null=True)),
                ('House_Location_map', models.CharField(blank=True, max_length=800, null=True)),
                ('House_type', models.CharField(default='2BHK/3BHK/SINGLE', max_length=100)),
                ('AllowedFor', models.CharField(default='All', max_length=100)),
                ('House_description', models.TextField(default='Write something About the facilities your renters will get there like electricity/Water etc')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(default='Not Mention', max_length=100)),
                ('location', models.CharField(default='Not Mention', max_length=100)),
                ('pin_no', models.IntegerField()),
                ('phone_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('Alt_phone_no', models.CharField(default='Not Mention', max_length=12, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('Price', models.IntegerField(default=1000)),
                ('Premium', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Reg_Mess_Restaurent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mess_name', models.CharField(max_length=200)),
                ('Mess_Owner_name', models.CharField(max_length=200)),
                ('Mess_description', models.TextField(blank=True, null=True)),
                ('Mess_address', models.TextField()),
                ('Mess_Location_link', models.URLField(blank=True, null=True)),
                ('Mess_Location_map_Code', models.CharField(blank=True, max_length=800, null=True)),
                ('Mess_img', models.ImageField(blank=True, null=True, upload_to='MessImg')),
                ('Landmark', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(default='Not Mention', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_no', models.IntegerField()),
                ('phone_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_Name', models.CharField(max_length=100, null=True)),
                ('Owner_pic', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('House_address', models.TextField()),
                ('House_video', models.FileField(blank=True, null=True, upload_to='Housevideos/%Y/%m/%d/', verbose_name='')),
                ('Building_img1', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('Room_img1', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('Room_img2', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('Room_img3', models.ImageField(blank=True, null=True, upload_to='Housepic')),
                ('Landmark', models.TextField()),
                ('House_Location_link', models.URLField(blank=True, null=True)),
                ('House_Location_map', models.CharField(blank=True, max_length=800, null=True)),
                ('House_type', models.CharField(default='2BHK/3BHK/SINGLE', max_length=100)),
                ('AllowedFor', models.CharField(default='All', max_length=100)),
                ('House_description', models.TextField(default='Write something About how good and what are the facilities your renters will get there like electricity/Water etc')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(default='Not Mention', max_length=100)),
                ('location', models.CharField(default='Not Mention', max_length=100)),
                ('pin_no', models.IntegerField()),
                ('phone_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('Alt_phone_no', models.CharField(default='Not Mention', max_length=12, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('Price', models.IntegerField(default=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Premium', models.BooleanField(default=False)),
                ('Active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reg_Mess_Restaurent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mess_name', models.CharField(max_length=200)),
                ('Mess_Owner_name', models.CharField(max_length=200)),
                ('Mess_description', models.TextField(blank=True, null=True)),
                ('Mess_address', models.TextField()),
                ('Mess_Location_link', models.URLField(blank=True, null=True)),
                ('Mess_Location_map_Code', models.CharField(blank=True, max_length=800, null=True)),
                ('Mess_img', models.ImageField(blank=True, null=True, upload_to='MessImg')),
                ('Landmark', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(default='Not Mention', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_no', models.IntegerField()),
                ('phone_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.city')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='dist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.district'),
        ),
    ]
