# Generated by Django 3.1.2 on 2021-09-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_premiumplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PremiumDaysLeft',
            field=models.CharField(blank=True, default='0 Days Left', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Premium_plan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_Validity',
            field=models.CharField(blank=True, default='No Plan Active', max_length=100, null=True),
        ),
    ]
