# Generated by Django 4.1.4 on 2023-07-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscribedpremiumplan_is_premium_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedpremiumplan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscribed_profile', to='accounts.profile'),
        ),
    ]
