# Generated by Django 4.1.4 on 2023-07-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subscribedpremiumplan_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Premium',
            new_name='premium',
        ),
        migrations.RemoveField(
            model_name='subscribedpremiumplan',
            name='is_Premium_active',
        ),
    ]
