# Generated by Django 4.1.4 on 2023-07-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_premium_profile_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedpremiumplan',
            name='is_premium_active',
            field=models.BooleanField(default=False),
        ),
    ]
